version: '3.9'

services:
  unittests:
    build: 
      dockerfile: Dockerfile-test 
      context: .
    environment:
      - ConnectionStrings:DB_Conn=${DB_Conn}
    entrypoint: ["bash","ModelTests/entrypoint-tests.sh", "--timeout=30"] 
    depends_on:
      - migration
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "P@ssword1"
      ACCEPT_EULA: "Y"
    ports:
      - "1620:1433"
  migration:
    image: flyway/flyway:8.5.2
    container_name: flyway_migration_julie
    volumes:
    - ./flyway/sql:/flyway/sql
    entrypoint: ["flyway","migrate"]      
    command: -user=sa -password=P@ssword1 -mixed=true -connectRetries=20 -url=jdbc:sqlserver://db;database=master 
    depends_on:
      - db
    
