FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal AS base
FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build


WORKDIR /src

# restore
COPY ["./API/Agilistas.csproj", "API/"]
RUN dotnet restore API/Agilistas.csproj
COPY ./ModelTests/ModelTests.csproj ./ModelTests/
RUN dotnet restore ModelTests/ModelTests.csproj

# copy src
COPY . .
RUN chmod +x ModelTests/wait-for-it.sh
RUN chmod +x ModelTests/entrypoint-tests.sh
